config/routes.rb
Rails.application.routes.draw do
  get 'pipeables/states', to: 'pipeables#states'
  resources :pipeables
  root to: 'pipeables#index'

end

app/models/pipeable.rb
class Pipeable < ActiveRecord::Base
  enum state: { lead: 0, thirty: 1, fifty: 2, eighty: 3, closed: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pipeables_helper.rb
module PipeablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PiperBrowserify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pipeables/_form.html.erb
<%= form_for(@pipeable) do |f| %>
  <% if @pipeable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pipeable.errors.count, "error") %> prohibited this pipeable from being saved:</h2>

      <ul>
      <% @pipeable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pipeables/edit.html.erb
<h1>Editing Pipeable</h1>

<%= render 'form' %>

<%= link_to 'Show', @pipeable %> |
<%= link_to 'Back', pipeables_path %>

app/views/pipeables/index.html.erb
<%= react_component 'Pipeables', data: @pipeables, url: 'pipeables.json', states_url: 'pipeables/states.json', pollInterval: 5000 %>

app/views/pipeables/new.html.erb
<h1>New Pipeable</h1>

<%= render 'form' %>

<%= link_to 'Back', pipeables_path %>

app/views/pipeables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pipeable.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pipeable.description %>
</p>

<p>
  <strong>State:</strong>
  <%= @pipeable.state %>
</p>

<%= link_to 'Edit', edit_pipeable_path(@pipeable) %> |
<%= link_to 'Back', pipeables_path %>